D:\Documents\GitHub\Bald-Guy-From-Die-Hard\Engine Model\Oxidizer Tank\TankAssembly-Static 1
D:\Documents\GitHub\Bald-Guy-From-Die-Hard\Engine Model\Oxidizer Tank\TankAssembly-Static 1
D:\Documents\GitHub\Bald-Guy-From-Die-Hard\Engine Model\Oxidizer Tank\Cylindrical Part-Static 1
D:\Documents\GitHub\Bald-Guy-From-Die-Hard\Engine Model\Oxidizer Tank\Cylindrical Part-Static 1
c:\users\dkola\appdata\local\temp\Assem1-Static 1
c:\users\dkola\appdata\local\temp\Assem1-Static 1
c:\users\dkola\appdata\local\temp\Assem1-Static 1
c:\users\dkola\appdata\local\temp\Assem1-Static 1
c:\users\dkola\appdata\local\temp\Assem1-Static 1
